version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - postgres

  adminer:
    build:
      context: ./adminer
      dockerfile: Dockerfile
    ports:
      - "8001:8000"

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: movies_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: wD4-CcLmvEd-kyH2JtV6
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - "6378:6379"

volumes:
  postgres-data:
