# Use official PostgreSQL image
FROM postgres:latest

# Set environment variables
ENV POSTGRES_DB=movies_db
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=wD4-CcLmvEd-kyH2JtV6

# Expose port 5432
EXPOSE 5432
